name: Rust

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: 
        cargo test --lib -- --test-threads=1
        cargo test --test multi_thread -- --test-threads=1
        cargo test --test archivation_rotation -- --test-threads=1

      

